import { Metadata as MetadataType } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";
import HeaderComponent from "@/components/HeaderComponent";
import { redirectData } from "@/data/utils-data";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: MetadataType = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "pt-16")}>
        <HeaderComponent redirectDatum={redirectData} />
        {children}
      </body>
    </html>
  );
}
