import { Metadata as MetadataType } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/HeaderComponent";
import { redirectData } from "@/data/utils-data";
import { cn } from "@/lib/utils";
import { introConfig } from "@/config/intro";

const inter = Inter({ subsets: ["latin"] });

export const metadata: MetadataType = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="Ja">
      <body className={cn(inter.className, "pt-16")}>
        {/* <HeaderComponent title={introConfig.title} mainNav={introConfig.mainNav} sidebarNav={introConfig.sidebarNav} /> */}
        {children}
      </body>
    </html>
  );
}
